apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-secret-config
data:
  nginx.conf.template: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 8080;
        location / {
          default_type text/plain;
          return 200 "Injected Secret: {$AWS_SECRET}\n";
        }
      }
    }