apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.23.0 # Replace with the desired version
      helm:
        values: |
          server:
            ha:
              enabled: true
              replicas: 2
              raft:
                enabled: true
                setNodeId: true
                config: |
                  ui = true
                  cluster_name = "vault-integrated-storage"
                  storage "raft" {
                    path = "/vault/data"
                  }

                  listener "tcp" {
                    address = "0.0.0.0:8200"
                    cluster_address = "0.0.0.0:8201"
                    tls_disable = "true"
                  }

            dataStorage:
              enabled: true
              storageClass: "standard"
              size: "5Gi"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
            affinity: {}

    - repoURL: https://charts.banzaicloud.com
      chart: vault-secrets-webhook
      targetRevision: 1.24.0 # Replace with the desired version
      helm:
        values: |
          env:
            VAULT_ADDR: "https://vault.vault.svc.cluster.local:8200"
          affinity: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

